"""SessionEnd and PreCompact hook: filter the session, then stage or spawn.

Code does the filtering, so nothing is judged out by mistake. What survives is
your words and the replies. Tool calls, results, file dumps, thinking and
anything this file does not recognise are dropped.

Then the mode in config.json decides who writes the entry:

    headless   spawn headless_run.py detached and get out of the way
    session    leave the text staged for your next session to write up

This hook returns in well under a second and always exits 0. A session is
never held up by its own memory.
"""

import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import common  # noqa: E402

# Harness written user events. None of these are you typing.
INJECTED = (
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<local-command-caveat>",
    "<command-message>",
    "<command-name>",
    "<command-args>",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
    "<user-prompt-submit-hook>",
    "<session-start-hook>",
    "<post-tool-use-hook>",
    "<task-notification>",
    "<teammate-message",
    "[Request interrupted",
    "Caveat: The messages below were generated by the user",
)

REMINDER = re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL)


def read_stdin():
    """The hook payload. Windows can hand us lone backslashes in a path."""
    raw = sys.stdin.read()
    try:
        return json.loads(raw)
    except ValueError:
        return json.loads(re.sub(r'(?<!\\)\\(?!["\\])', r"\\\\", raw))


def text_blocks(content):
    """Text out of a message. Every other kind of block is dropped."""
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return ""
    parts = []
    for block in content:
        if isinstance(block, dict) and block.get("type") == "text":
            value = block.get("text")
            if isinstance(value, str):
                parts.append(value)
    return "\n".join(parts)


def turns(transcript):
    """The conversation out of the transcript, in order. Default is to drop."""
    kept = []
    with Path(transcript).open(encoding="utf-8", errors="replace") as handle:
        for raw in handle:
            line = raw.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except ValueError:
                continue
            if not isinstance(event, dict):
                continue
            if event.get("isSidechain") is True:  # a sub agent's own talk
                continue
            if event.get("type") not in ("user", "assistant"):
                continue
            if event.get("toolUseResult") is not None:  # a tool result carrier
                continue
            if event.get("isMeta") is True or event.get("isCompactSummary") is True:
                continue
            message = event.get("message")
            if not isinstance(message, dict):
                continue
            role = message.get("role")
            if role not in ("user", "assistant"):
                continue
            body = text_blocks(message.get("content")).strip()
            if role == "user":
                body = REMINDER.sub("", body).strip()
                if body.startswith(INJECTED):
                    continue
            if not body:
                continue
            kept.append(("You" if role == "user" else "Claude", body))
    return kept


def filtered(transcript, cfg):
    """The last turns, cut to the character budget, keeping the end."""
    recent = turns(transcript)[-cfg["max_turns"] :]
    if len(recent) < cfg["min_turns"]:
        return None
    text = "\n\n".join(f"**{who}:** {body}" for who, body in recent)
    if len(text) > cfg["max_chars"]:
        text = text[-cfg["max_chars"] :]
        cut = text.find("\n\n**")  # start at a whole turn, never mid sentence
        if cut > 0:
            text = text[cut + 2 :]
    return text


def spawn(staged):
    """Run the write up detached, so closing the session does not wait on it."""
    common.LOG.mkdir(parents=True, exist_ok=True)
    handle = (common.LOG / f"{staged.stem}.out").open("ab")
    extra = {}
    if os.name == "nt":
        extra["creationflags"] = (
            subprocess.DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP
        )
    else:
        extra["start_new_session"] = True
    subprocess.Popen(
        # -u so the log fills as it goes, not only when the run finishes
        [sys.executable, "-u", str(HERE / "headless_run.py"), str(staged)],
        stdin=subprocess.DEVNULL,
        stdout=handle,
        stderr=handle,
        close_fds=True,
        **extra,
    )


def main():
    if os.environ.get("MEMORY_STARTER_CHILD"):  # our own headless call closing
        return
    try:
        payload = read_stdin()
    except Exception:
        return
    transcript = payload.get("transcript_path") or ""
    session_id = str(payload.get("session_id") or "session")
    if not transcript or not Path(transcript).is_file():
        return

    cfg = common.config()
    notes = common.corpus()
    if notes is None:  # no index yet, so nowhere for an entry to live
        return
    try:
        text = filtered(transcript, cfg)
    except Exception as exc:
        common.note_failure("session_end", f"{type(exc).__name__} {exc}")
        return
    if not text:
        return

    # the stamp matters: one long session can close twice, once before a
    # compaction and once at the end, and neither half may overwrite the other
    safe = re.sub(r"[^A-Za-z0-9_-]+", "-", session_id)[:64] or "session"
    common.PENDING.mkdir(parents=True, exist_ok=True)
    staged = common.PENDING / f"{safe}-{datetime.now():%Y%m%d-%H%M%S}.md"
    staged.write_text(text, encoding="utf-8")

    if cfg["mode"] == "headless":
        try:
            spawn(staged)
        except Exception as exc:
            common.note_failure("session_end", f"spawn: {type(exc).__name__} {exc}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # a session close is never blocked by this
        common.note_failure("session_end", f"{type(exc).__name__} {exc}")
    sys.exit(0)
